services:
  - type: web
    name: sistema-examenes-api
    runtime: docker
    dockerfilePath: ./Backend/Dockerfile
    dockerContext: ./Backend
    autoDeploy: true
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
